apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "meteonow.componentname" (dict "name" "deployment" "releaseName" .Release.Name) }}
  labels:
    app.kubernetes.io/name: {{ include "meteonow.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "meteonow.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        {{- if .Values.vault.enabled }}
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/log-level: debug
        vault.hashicorp.com/role: {{ .Values.vault.role | quote }}
        vault.hashicorp.com/agent-inject-secret-API_KEY: {{ .Values.vault.secretPath | quote }}
        vault.hashicorp.com/agent-inject-template-API_KEY: |
          {{`{{- with secret "`}}{{ .Values.vault.secretPath }}{{`" -}}`}}
          {{`{{ .Data.data.API_KEY }}`}}
          {{`{{- end }}`}}
        {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "meteonow.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "meteonow.componentname" (dict "name" "sa" "releaseName" .Release.Name) }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
              name: http
{{- if not .Values.vault.enabled }}
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: not-used
                  key: not-used
{{- end }}

          resources:
{{- toYaml .Values.resources | nindent 12 }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{- toYaml . | nindent 8 }}
{{- end }}