
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "meteonow.componentname" (dict "name" "sa" "releaseName" .Release.Name) }}
  labels:
    app.kubernetes.io/name: {{ include "meteonow.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
