apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-prod
  namespace: tostack-argocd
spec:
  project: default
  source:
    repoURL: git@github.com:GitStormOrg/argocd.git
    targetRevision: main
    path: base/monitoring
    helm:
      valueFiles:
        - ../../overlays/prod/monitoring/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true