server:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod-cloudflare
    hosts:
      - host: vault.maxcaptab.com
        paths:
          - /
    tls:
      - hosts:
          - vault.maxcaptab.com
        secretName: vault-tls

  certificate:
    enabled: true
    issuer:
      group: cert-manager.io
      kind: ClusterIssuer
      name: letsencrypt-prod-cloudflare

  dataStorage:
    enabled: true
    storageClass: csi-cinder-classic
    accessMode: ReadWriteOnce
    size: 10Gi

  serviceAccount:
    create: true
    name: vault-auth

  authDelegator:
    enabled: true

  vault:
    address: "http://vault.vault-prod.svc:8200"
    authPath: "auth/kubernetes"

  kubernetesHost: "https://kubernetes.default.svc"
