apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "microservice1-couscous.fullname" . }}
  labels:
    app: {{ include "microservice1-couscous.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "microservice1-couscous.name" . }}
  template:
    metadata:
      annotations:
      {{- if .Values.vault.enabled }}
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "couscous"
        # Chemin(s) Vault à récupérer
        vault.hashicorp.com/agent-inject-secret-db-env: "secret/data/postgres"    # mount = secret/
        vault.hashicorp.com/agent-inject-template-db-env: |
          {{`{{- with secret "secret/data/postgres" -}}
          DB_HOST={{ .Data.data.DB_HOST }}
          DB_PORT={{ .Data.data.DB_PORT }}
          DB_NAME={{ .Data.data.DB_NAME }}
          DB_USER={{ .Data.data.DB_USER }}
          DB_PASSWORD={{ .Data.data.DB_PASSWORD }}
          {{- end }}
      labels:
        app: {{ include "microservice1-couscous.name" . }}
    spec:
      serviceAccountName: {{ include "microservice1-couscous.serviceAccountName" . }}
      imagePullSecrets:
        {{- if .Values.imagePullSecrets }}
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
        {{- end }}
      containers:
        - name: {{ include "microservice1-couscous.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: PORT
              value: "{{ .Values.service.port }}"
