apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "node-express.fullname" . }}
  labels:
    app: {{ include "node-express.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "node-express.name" . }}
  template:
    metadata:
      annotations:
        # Activation de l'injection Vault
        vault.hashicorp.com/agent-inject: "true"
        # Rôle Kubernetes utilisé par Vault
        vault.hashicorp.com/role: "my-k8s-role"
        # Chemin du secret à injecter depuis Vault
        vault.hashicorp.com/agent-inject-secret-postgres: "secrets/data/postgres"
        # Ce bloc sera injecté tel quel et évalué par Vault Agent
        vault.hashicorp.com/agent-inject-template-postgres: |
          {{"{{"}}- with secret "secret/data/postgres" -{{"}}"}}
          {{"{{"}} .Data.data.POSTGRES_URL {{"}}"}}
          {{"{{"}}- end {{"}}"}}
      labels:
        app: {{ include "node-express.name" . }}
    spec:
      containers:
        - name: {{ include "node-express.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: PORT
              value: "{{ .Values.service.port }}"
