apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "node-express.fullname" . }}
  labels:
    app: {{ include "node-express.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "node-express.name" . }}
  template:
    metadata:
      annotations:
        # Activation de l'injection Vault
        vault.hashicorp.com/agent-inject: "true"
        # Rôle Kubernetes défini dans Vault
        vault.hashicorp.com/role: "my-k8s-role"
        # Chemin du secret dans Vault (KV Version 2 ici)
        vault.hashicorp.com/agent-inject-secret-postgres: "secret/data/postgres"
        # Template pour extraire uniquement la clé POSTGRES_URL du secret
        vault.hashicorp.com/agent-inject-template-postgres: |
          {{- with secret "secret/data/postgres" -}}
          {{ .Data.data.POSTGRES_URL }}
          {{- end }}
      labels:
        app: {{ include "node-express.name" . }}
    spec:
      containers:
        - name: {{ include "node-express.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          # Vous pouvez ajouter d'autres variables d'environnement ici si nécessaire
          env:
            - name: PORT
              value: "{{ .Values.service.port }}"
      # Le Vault Agent Injector monte automatiquement les secrets dans /vault/secrets dans le pod.
