{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "microservice1-couscous.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host.host | default $host }}
      http:
        paths:
          {{- if $host.paths }}
            {{- range $p := $host.paths }}
            - path: {{ $p | quote }}
              pathType: Prefix
              backend:
                service:
                  name: {{ include "microservice1-couscous.fullname" $ }}
                  port:
                    number: {{ $.Values.service.port }}
            {{- end }}
          {{- else }}
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: {{ include "microservice1-couscous.fullname" $ }}
                  port:
                    number: {{ $.Values.service.port }}
          {{- end }}
    {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
{{- end }}
