standalone:
  enabled: true
  # config is a raw string of default configuration when using a Stateful
  # deployment. Default is to use a PersistentVolumeClaim mounted at /vault/data
  # and store data there. This is only used when using a Replica count of 1, and
  # using a stateful set.
  config: |-
    ui = true

    listener "tcp" {
      tls_disable = 1
      address = "[::]:8200"
      cluster_address = "[::]:8201"
      # Enable unauthenticated metrics access (necessary for Prometheus Operator)
      # telemetry {
      #   unauthenticated_metrics_access = "true"
      # }
    }
    storage "file" {
      path = "/vault/data"
    }
    
server:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: vault.spreadit.ovh
        paths:
          - /
    tls:
      - hosts:
          - vault.spreadit.ovh
        secretName: vault-tls

  certificate:
    enabled: true
    issuer:
      group: cert-manager.io
      kind: ClusterIssuer
      name: letsencrypt-prod

  dataStorage:
    enabled: true
    storageClass: local-path
    accessMode: ReadWriteOnce
    size: 10Gi

vault:
  auth:
    enabled: false # Toggle pour activer la configuration automatique de Vault auth/kubernetes
