server:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: vault.spreadit.ovh
        paths:
          - /
    tls:
      - hosts:
          - vault.spreadit.ovh
        secretName: vault-tls

  certificate:
    enabled: true
    issuer:
      group: cert-manager.io
      kind: ClusterIssuer
      name: letsencrypt-prod

  dataStorage:
    enabled: true
    storageClass: csi-cinder-classic
    accessMode: ReadWriteOnce
    size: 10Gi

vault:
  auth:
    enabled: false # Toggle pour activer la configuration automatique de Vault auth/kubernetes
