apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-auth-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vault-auth-clusterrole
subjects:
  - kind: ServiceAccount
    name: vault-auth
    namespace: {{ .Release.Namespace }}
