{{- if and .Values.vault (hasKey .Values.vault "auth") (or .Values.vault.auth.enabled false) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: {{ .Release.Namespace }}
{{- end }}
