serviceAccount:
  create: false        # on l’a créé à la main
  name: couscous-sa

primary:
  automountServiceAccountToken: true   # par sécurité si le chart le supporte

  podAnnotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-inject-token: "true"
    vault.hashicorp.com/role: "couscous"
    vault.hashicorp.com/agent-inject-secret-db-creds: "secrets/data/postgres"
    vault.hashicorp.com/agent-inject-template-db-creds: |
      {{`{{- with secret "secrets/data/postgres" -}}
      export POSTGRES_PASSWORD="{{ .Data.data.POSTGRES_PASSWORD }}"
      {{- end}}`}}

  extraEnvVars:
    - name: BASH_ENV                # Bash lira automatiquement ce fichier
      value: /vault/secrets/db-creds

  persistence:
    enabled: false          # ou false si tu veux seulement un emptyDir
    size: 8Gi              # laisse 8 Gi si c’est ce que tu veux
    storageClass: local-path