server:
  ha:
    enabled: true
    replicas: 2
    raft:
      enabled: true

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-staging-cloudflare
    hosts:
      - host: vault.maxcaptab.com
        paths:
          - /
    tls:
      - hosts:
          - vault.maxcaptab.com
        secretName: vault-server-tls

  certificate:
    enabled: true
    issuer:
      group: cert-manager.io
      kind: ClusterIssuer
      name: letsencrypt-staging-cloudflare

  dataStorage:
    storageClass: standard
    accessMode: ReadWriteOnce
    size: 10Gi
