apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:GitStormOrg/argocd.git
    targetRevision: remaster
    path: ../base/vault
    chart: .
    helm:
      valueFiles:
        - ../overlays/prod/vault/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: vault-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
