apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-prod
  namespace: argocd
spec:
  project: devops-project
  source:
    repoURL: https://helm.releases.hashicorp.com 
    chart: vault
    targetRevision: 0.27.0
    helm:
      values: |
        server:
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
              cert-manager.io/cluster-issuer: letsencrypt-staging-cloudflare
            hosts:
              - host: vault.maxcaptab.com
                paths:
                  - /
            tls:
              - hosts:
                  - vault.maxcaptab.com
                secretName: vault-tls
          certificate:
            enabled: true
            issuer:
              group: cert-manager.io
              kind: ClusterIssuer
              name: letsencrypt-staging-cloudflare
          dataStorage:
            enabled: true
            accessMode: ReadWriteOnce
            size: 10Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: vault-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
